names = """Yara Liu
Pedro Espinoza
Lucille McKee
Bjorn Rasmussen
Esperanza Lynch
Zane Gardner
Jordyn Garrett
Kairo Patton
Lorelei Watts
Dakota Reilly
Tori Gentry
Magnus Mack
Nadia Bradley
Richard Leblanc
Novalee Montoya
Ford Terry
Wren Terrell
Jaxen Calderon
Serena Clay
Yosef Ho
Calliope Kim
Roman Espinoza
Lucille Torres
Jayden Berry
Annabelle Conner
Phillip Figueroa
Lilith Hess
Lawrence Robles
Felicity Chung
Ira Dougherty
Alisson Kent
Mekhi Bridges
Elora Stewart
Nolan Walton
Scarlet Sanchez
Joseph Jacobson
Royal Travis
Willie Navarro
Winter Rhodes
Titus Proctor
Chandler Hopkins
Ali Nielsen
Vienna Shepard
Damari Potts
Ellison Kerr
Louie Howard
Sophie Booth
Chaim Gregory
Alaya Cox
Connor Gonzales
Hadley Sosa
Emir Horne
Marlowe Douglas
Derek Sloan
Selene Chandler
Royal Ahmed
Jolie Roach
Caspian Medrano
Halle Roth
Roy Ochoa
Luciana McLean
Crosby Mayo
Aarya O'Neal
Eddie McPherson
Emmaline Gonzalez
Ethan Dean
Julianna Boyd
Dean Lynn
Samira Moon
Nova Espinosa
Braylee Beasley
Stanley Rocha
Emmie Patterson
Amir Burgess
Emory Conrad
Dilan Singleton
Malaysia Wiggins
Azariah Velasquez
Esme Adkins
Kylo Melton
Kamiyah Lewis
Wyatt Hensley
Malaya Holland
Brady Cruz
Claire Bell
Emmett Moody
Elaine Good
Davian Marquez
Milani Giles
Kole Cruz
Claire Leonard
Ricardo Morrison
Rebecca Dyer
Atreus Hebert
Kyleigh Ramsey
Luciano Gilmore
Chanel Gonzalez
Ethan Carpenter
Lilly Jennings
Corbin Holt
Adelynn Reeves
Clark Rangel
Gloria McCoy
Jett McIntosh
Gwen Ross
Wesley Mueller
Imani Austin
Omar Reeves
Lana Roy
Marcelo Martin
Mila Merritt
Colten Parks
Ainsley Lowery
Jaxxon Gates
Melina Garcia
James Villa
Johanna Saunders
Kasen Harris
Penelope Boyle
Robin Harris
Penelope McLean
Crosby Phillips
Naomi Dawson
Iker Daniel
Joy Kramer
Kylan Blankenship
Rosalee Nixon
Cory Bernard
Barbara Miranda
Rory Melendez
Bethany McCann
Heath Castillo
Eva Odom
Kylian Koch
Milana Chapman
Knox Copeland
Dayana Woodward
Jeremias Ahmed
Jolie Cline
Cullen Hester
Zendaya Barrera
Makai Haynes
Lexi Skinner
Ridge Arnold
Finley Berg
Cayson Myers
Lydia Beard
Nathanael Mathews
Sloan Conrad
Dilan Gaines
Aya Good
Davian Lynch
Malia Cox
Connor McBride
Kelsey Humphrey
Krew Larsen
Xiomara Hammond
Francis Huffman
Hayley Myers
Adam Daniels
Ember Potts
Alfred Hoover
Virginia Wagner
Enzo Novak
Kaiya Ballard
Kenzo Patterson
Kaylee Hart
Joel Jensen
Jane Lin
Conor Bailey
Kennedy Olson
Malachi Cruz
Claire Ware
Tadeo Woods
Reese West
Diego Nash
Novah Cummings
Raiden Yates
Charley Orozco
Keanu Hancock
Katelyn Quinn
Rhys Khan
Mabel Sherman
Adan Holland
Mariah Clark
John Floyd
Yaretzi Frye
Franco Cain
Kendra Calhoun
Gary Neal
Talia Gardner
Alan Xiong
Amayah Wolfe
Donovan Malone
Skyler Roberson
Shepherd Weeks
Karen Everett
Camilo Farley
Wrenley Beck
Eduardo Hail
Lainey Lucero
Felipe Daugherty
Magdalena Maxwell
Eden Flowers
Ariya Gray
Nicholas Garrett
Tessa Garrison
Noe Chung
Rivka Greene
Griffin Sanders
Everleigh Woodward
Jeremias Gomez
Natalie Graham
Giovanni Gonzalez
Abigail Colon
Bruce Weeks
Karen Arellano
Kellan Colon
Remy Turner
Joshua Ross
Peyton Kent
Mekhi Hall
Leah Munoz
Justin Middleton
Madalyn Wiggins
Azariah Reynolds
Isabelle Ballard
Kenzo Andrade
Emmy Bowen
Trevor Vincent
Allyson Gregory
Travis Baker
Isla McFarland
Dane Lewis
Ellie Branch
Keenan Blair
Frances Gibson
Tyler White
Layla Hill
Isaac Delgado
Alani Logan
Rocco Trejo
Rosalyn Hancock
Rex Nielsen
Vienna Ahmed
Harry Mora
Jemma Woodward
Jeremias Goodman
Carolina Velez
Kareem Costa
Robin Buck
Jon Saunders
Meadow Sierra
Dayton Lucero
Ila Murray
Ashton Rocha
Emmie Quintero
Thatcher Shaffer
Alanna Yu
Bryant Chen
Valeria Peters
Patrick Ross
Peyton Donovan
Brayan Gomez
Natalie Summers
Darius Marquez
Milani Browning
Rohan Johnson
Emma Fowler
Kameron Horn
Avah Davis
Lucas Hudson
Kamila Horton
Garrett Kirk
Ellis Humphrey
Krew Dickerson
Opal Larsen
Brycen Webb
Ariella Dodson
Seven Molina
Alexandria Russo
Jamie Roy
Savanna Garner
Sage Leblanc
Novalee Cantrell
Harris Valenzuela
Henley Ortega
Kobe Stevenson
Regina Luna
Erick Hodge
Coraline Correa
Zakai McKenzie
Briar Farmer
Jamison Rodriguez
Evelyn O'Donnell
Lian Nunez
Mya Hutchinson
Korbin Delgado
Alani Russo
Jamie Hardin
Vada Thornton
Malik Hester
Zendaya Kim
Roman Newton
Braelynn Clark
John Noble
Hunter Horton
Garrett Carter
Lucy Walls
Larry Chambers
Makayla Mendoza
Dominic Rivera
Lillian Berry
Adonis Bridges
Elora Pham
Russell Solomon
Mylah Beard
Nathanael McKee
Kori Acosta
Jensen Spencer
Alyssa Adkins
Kylo Lambert
Nina Terrell
Jaxen McConnell
Denise Bishop
Paxton Atkins
Mina Patterson
Amir Duffy
Addisyn Larson
Rafael Whitehead
Sylvie Gomez
Isaiah Brewer
Thea Dyer
Atreus Nielsen
Vienna Acevedo
Dakari Quintero
Keyla Goodwin
Kaison David
Haylee Chavez
Ian Blankenship
Rosalee Enriquez
Elisha Stafford
Bridget Patterson
Amir Terrell
Paityn Rubio
Titan Spence
Aislinn Barrett
Angelo Cisneros
Janelle Andrade
Abdiel Chan
Hattie Berry
Adonis Schmidt
Kimberly Guerra
Leland Dennis
Maisie Burch
Gerald Bailey
Kennedy Wolfe
Donovan Valdez
Diana Roach
Caspian Landry
Brynleigh Schneider
Raymond Kemp
Anika Davidson
Dante Blackwell
Saoirse Grant
Leon Ryan
Morgan McKee
Bjorn George
Adelyn Bowers
Dorian Odom
Laylani Stewart
Nolan McLaughlin
Stephanie Fox
Antonio Harrington
Legacy Chavez
Ian Quinn
Heaven Christian
Ledger Espinosa
Braylee Benjamin
Kyro Avila
Amiyah Ramsey
Luciano Logan
Kora Andrade
Abdiel Torres
Violet Warner
Jaxton Todd
Zariah Townsend
Alexis Moyer
Zola Dickson
Maxton Chen
Valeria Carey
Watson Chan
Hattie Kramer
Kylan Corona
Marianna Simon
Zayne Fernandez
Amara Sanchez
Joseph Bowers
Elisa Herrera
River Maynard
Carolyn Kramer
Kylan Caldwell
Evelynn Powers
Sean Wolf
Jolene Mitchell
Jaxon Hart
Gemma Lyons
Cyrus Benson
Collins O'Connell
Jovanni Powers
Michelle Woods
Zion Farmer
Madelynn Robertson
Emiliano Larsen
Xiomara Walter
Lochlan Ibarra
Madilynn Moyer
Ahmir Pittman
Marie Taylor
Jackson Collier
Ivory Blake
Zyaire Bernal
Emmeline Mason
Brandon Khan
Mabel Esquivel
Bridger Roberson
Sasha Fox
Antonio Keller
Logan Koch
Salvador Stone
Catalina Wiggins
Azariah Wilkerson
Janiyah Ho
Morgan Perez
Eleanor Reyna
Reginald Liu
Kate Nixon
Cory Villalobos
Zoya Castro
Jasper McPherson
Emmaline Cole
Nathaniel Valentine
August Conway
Orlando Macias
Adley Noble
Idris Robles
Felicity Ballard
Kenzo Lawrence
Lauren Cantrell
Harris Green
Zoe Eaton
Leighton Dyer
Estrella Jones
William Coffey
Paola Atkins
Cason Carr
Rowan Galindo
Salvatore Porter
Ryleigh Baxter
Tomas Pham
Raelyn Harding
Brodie Flynn
Dorothy Pitts
Trey Ray
Ruth Snyder
Thiago Aguilar
Josie Rowland
Eliezer Diaz
Elena Bender
Zavier Pacheco
Paris Rodriguez
Henry O'Neal
Treasure James
Jaxson O'brien
Joanna Lam
Bodie Villanueva
Monroe Anderson
Jacob Wade
Evie Thomas
Logan Berg
Emmalyn Alvarez
Xavier Nava
Scout Mercado
Abram Hull
Andi Schaefer
Ishaan Jaramillo
Guadalupe Lin
Conor Burke
Vera Benson
Desmond Liu
Kate Wise
Frederick Love
Avianna Green
Anthony Sims
Lena Morrison
Maximus Schneider
Delaney Ingram
Tripp Hoover
Virginia Whitaker
Keith Stanton
Jaycee Richards
Holden Harding
Aniya Mann
Nehemiah Middleton
Madalyn Small
Rudy Higgins
Leighton Cross
Fabian Peralta
Malayah Ball
Shane Olson
Isabel Yoder
Johan Murphy
Bella Vincent
Aarav Calderon
Serena Ibarra
Asa Farley
Wrenley Heath
Lionel Ochoa
Luciana Greer
Koda Bowers
Elisa Winters
Deandre Reid
Charlee Dudley
Colter Quintana
Kenia Burnett
Davis Black
Molly Randall
Trenton Callahan
Kimber Barr
Harley Yu
Navy Ventura
Branson Henry
Summer Browning
Rohan Rowe
Matilda Golden
Amias Dougherty
Alisson Shelton
Leonel Horton
Aitana Suarez
Soren Harmon
Maren Pollard
Jad Ramirez
Grace Ryan
Timothy Fields
Annie Sweeney
Nixon Perkins
Sage Perez
Owen Gaines
Aya Yu
Bryant Schwartz
Lilliana Wilson
Daniel Cortes
Lea Horton
Garrett Long
Jade Craig
Odin Hudson
Kamila Shah
Zain Williamson
Catherine Snow
Houston Skinner
Mara Baker
Ezra Humphrey
Journi Walters
Colson Meadows
Pearl Chang
Ari Zuniga
Leslie Carroll
Oscar Sierra
Marceline Ward
Jameson Arroyo
Kyra Graves
Cesar Lucero
Ila Gomez
Isaiah Esparza
Ramona Silva
Luka McConnell
Denise Best
Harlem Perez
Eleanor Rivera
Charles Spears
Isabela Harvey
Cayden Marks
Monica Alfaro
Xzavier Berry
Annabelle Vo
Gordon Bell
Melody Dickerson
Flynn Lynch
Malia Good
Davian Travis
Mazikee Friedman
Darwin Watts
Melissa Truong
Ayan Wheeler
Sydney Page
Pablo Myers
Lydia Skinner
Ridge Green
Zoe Cortes
Banks Chen
Valeria Thompson
Theodore Fernandez
Amara Bravo
Genesis Andersen
Zoie Wiggins
Azariah Brooks
Autumn Cummings
Raiden Rollins
Araceli Gill
Matthias Hutchinson
Jamie Fry
Jacoby Medrano
Halle Bernal
Eithan Cherry
Nyomi Spencer
Ace Mejia
Saylor O'brien
Riley Rice
Ada Leonard
Ricardo Good
Nathalia Strong
Axl Maxwell
Kyla Pacheco
Erik Dickerson
Opal Williams
Oliver Short
Cheyenne McClure
Reese Webster
Kensley Foster
Kayden Russell
Raelynn Cortez
Zayn Hawkins
Ariel Harris
Samuel Garza
River Rogers
Colton Travis
Mazikee Roberson
Shepherd Ventura
Zora Kirk
Alessandro Hayes
Iris Curry
Briggs Murillo
Mikaela Lucero
Felipe Ashley
Khalani Shannon
Eliel Hensley
Malaya Schroeder
Izaiah Hale
Brinley Mejia
Atticus Villa
Johanna Kelly
Cooper Hensley
Malaya Cline
Cullen McKenzie
Briar Lindsey
Jayson Spence
Aislinn Hurley
Van Stanley
Gracelyn Golden
Amias Hart
Gemma Walter
Lochlan Fry
Clarissa Vazquez
Jesse McConnell
Denise Gilmore
Vihaan Payne
London Farmer
Jamison Rojas
Adaline Hickman
Jakobe Todd
Zariah Montoya
Ford Pollard
Marisol Saunders
Kasen Cole
Margaret Beard
Nathanael Bernard
Barbara David
Alonso Spears
Isabela Griffin
Ayden Larsen
Xiomara Vang
Jimmy Hutchinson
Jamie Tate
Dalton Dawson
Veronica Houston
Sylas Lynch
Malia Clarke
Stetson Landry
Brynleigh Knox
Valentin Parks
Ainsley Huffman
Chris Rich
Sunny Camacho
Tatum Golden
Giuliana Raymond
Maurice Kim
Gabriella Powell
Bennett Turner
Brooklyn French
Corey Good
Nathalia Huang
Ayaan Wells
Cecilia Zimmerman
Sergio Valentine
August Lane
Matias Pineda
Nola Peck
Yousef Lara
Heidi Orozco
Keanu Boyer
Chaya Patterson
Amir Curtis
Alexis Morgan
Hunter James
Quinn McBride
Denver Navarro
Winter Garner
Sage Brooks
Autumn Yoder
Johan Barron
Anya Peters
Patrick Hardin
Vada Martin
Mateo Vega
Dakota Huynh
Layton Burnett
Emberly Kane
Brock Franco
Charleigh Bell
Emmett Rollins
Araceli Ward
Jameson Parsons
Maia Patrick
Derrick Macdonald
Rosalia Burgess
Kolton Pitts
Nala Cole
Nathaniel Bass
Zahra Keller
Nico Chavez
Nevaeh Cano
Terry Chavez
Nevaeh Gray
Nicholas Doyle
Annalise Huynh
Layton Lim
Giavanna Howard
Jeremiah Compton
Elina Best
Harlem Pierce
Arabella Blair
Troy Baker
Isla Baker
Ezra Gilmore
Chanel Villegas
Clyde McFarland
Annika Espinosa
Khalid Chavez
Nevaeh Jenkins
Declan Wiley
Lauryn Sandoval
Brantley Herman
Paulina Dominguez
Kaden Hernandez
Camila Parker
Caleb Lewis
Ellie Espinosa
Khalid Hurst
Adalee Baldwin
Jaiden Barron
Anya Esquivel
Bridger Walter
Penny Luna
Erick Sanford
Emerald Castillo
Kai McDonald
Daisy Harrington
Omari Horn
Avah Reid
Josue Glenn
Blaire Burgess
Kolton Powell
Vivian McCoy
Jett Marin
Celia Wright
Grayson Francis
Daniella Joseph
Kyle Keller
Logan Camacho
Tatum Douglas
Aniyah Clements
Fisher Horton
Aitana Ballard
Kenzo Dorsey
Addyson Huffman
Chris Person
Dylan Blackburn
Zahir Larsen
Xiomara Pace
Dior Enriquez
Nellie Cameron
Rayan Thompson
Madison Wilkins
Yusuf Macdonald
Rosalia Bonilla
Aden Valenzuela
Henley Dillon
Alvin Mathis
Anne Glass
Allan Macdonald
Rosalia Wheeler
Kenneth Webster
Kensley Crane
Fox Patel
Madeline Harmon
Roberto Schroeder
Cameron Donovan
Brayan Chambers
Makayla Landry
Jaxx Olsen
Oaklyn Stafford
Alfredo Fernandez
Amara Sheppard
Trent Dunn
Olive Fields
Clayton Myers
Lydia Pearson
Gunner Burton
Miriam Arroyo
Alberto Garrett
Tessa Villanueva
Huxley Rhodes
Tatum Espinosa
Khalid Dejesus
Julissa Carrillo
Wade Wilkerson
Janiyah Moody
Ryland Webster
Kensley Hines
Uriel Villa
Johanna Warner
Jaxton Perry
Clara Macias
Moshe Chavez
Nevaeh Roth
Roy Cantrell
Yamileth Hill
Isaac Medrano
Halle Peters
Patrick Carpenter
Lilly Vargas
Ryker Conway
Ryann McKee
Bjorn Phan
Elsa Mata
Ray Fry
Clarissa Bradshaw
Emory Reeves
Lana Gilbert
Tobias Benson
Collins Whitaker
Keith Middleton
Madalyn Curry
Briggs Frank
Dior Davenport
Dariel Kerr
Baylee Bradley
Richard Medrano
Halle Hancock
Rex Esquivel
Jaylee Proctor
Vance Walters
Samara Boyd
Dean Wilson
Luna Sherman
Adan Roth
Elliot Trujillo
Apollo Chase
Angie Montgomery
Maximiliano Mays
Denisse McFarland
Dane Sparks
Aisha Cain
Benson Nunez
Mya Farmer
Jamison Quinn
Heaven Lozano
Boone Short
Cheyenne Bates
Ellis Barron
Anya Malone
Ruben Sanders
Everleigh McDonald
Calvin Garner
Jacqueline Saunders
Kasen Weaver
Teagan Craig
Odin Ellison
Raina Petersen
Samson Combs
Irene McDaniel
Major Bennett
Josephine Farmer
Jamison Blackburn
Frida Castro
Jasper Woodard
Aubrie Horton
Garrett Sims
Lena Griffin
Ayden Good
Nathalia Chung
Ira Ingram
Katie Singleton
Landyn Leon
Amora Skinner
Ridge Shaw
Emersyn Sullivan
Evan Lozano
Cecelia Myers
Adam Francis
Daniella Moon
Nova Medina
Elliana Fernandez
Bentley Winters
Kataleya Burgess
Kolton Arellano
Faye Hammond
Francis Lane
Amy Welch
Hendrix Kent
Jazmine Walsh
Bodhi Delarosa
Iyla English
Junior McClain
Marleigh Blevins
Avi Lowery
Estelle Frost
Dario Lewis
Ellie Harvey
Cayden Leach
Martha Kemp
Melvin Davila
Rayne Moses
Niklaus Pineda
Nola Allison
Dennis King
Victoria Ashley
Kylen Robbins
Stevie Moyer
Ahmir Bush
Everlee Thomas
Logan Stevens
Katherine Neal
Kane Rowland
Harleigh Reyna
Reginald Peralta
Malayah Ashley
Kylen Hampton
Leona Hines
Uriel Nunez
Mya Kline
Ramon Zamora
Sierra Ortega
Kobe Fitzpatrick
Annabella Barnes
Damian Rollins
Araceli Lowery
Jaxxon Poole
Bonnie Duffy
Kyng Arroyo
Kyra Hendricks
Dash Ho
Calliope Estrada
Phoenix Horton
Aitana Velez
Kareem Houston
Lylah Case
Bentlee Wright
Lily Macias
Moshe Simon
Kalani Costa
Kenji Curry
Alison Kemp
Melvin Conner
Alondra Reese
Alijah Wheeler
Sydney Zimmerman
Sergio Poole
Bonnie Gibbs
Deacon Cain
Kendra Pennington
Bobby Pace
Giana Estes
Hakeem Owens
Amaya Norris
Cairo McKenzie
Briar Pace
Dior Munoz
Kehlani Valencia
Dax Gibbs
"""


stringAddresses = """Station Road
King Edward Road
Winchester Road
Cambridge Street
Farm Close
Orchard Place
Granville Street
Meadway
Derby Road
Greenhill Road
Hall Road
Lichfield Road
Mill Street
School Hill
Canterbury Close
Castle Lane
St Michael's Close
George Street
Brook Lane
Windmill Close
Rectory Lane
High Lane
Lime Close
Derwent Avenue
Nursery Road
Victoria Street
The Avenue
St Andrews Close
Church Avenue
Cavendish Road
Swan Street
Waverley Road
Stafford Road
Albert Street
Park Close
Turner Street
Rowan Avenue
Gainsborough Road
Priory Gardens
Holly Close
Sycamore Avenue
Barton Close
Smithy Lane
St Margaret's Road
Green Road
Hill Lane
The Rowans
Park Lane
Elizabeth Road
Tennyson Road
Water Lane
Albert Road
Lime Avenue
Church Drive
Middle Road
Bedford Street
Lodge Lane
St John's Close
Meadow Lane
Oak Lane
First Avenue
Trinity Street
Marsh Lane
Clarendon Road
Primrose Hill
The Grange
Mansfield Road
East Street
Vale Road
Beechwood Close
North Avenue
Honeysuckle Close
Richmond Avenue
Chichester Close
Commercial Road
Grange Drive
Woodlands Avenue
Moorland Road
Chestnut Avenue
New Street
Pound Lane
The Cloisters
Warren Road
Commercial Street
Oakwood Close
York Road
Hill Street
Douglas Road
York Street
Willow Drive
Stoney Lane
Stafford Street
Clifton Road
Market Place
Severn Road
Brookside
Brown Street
Woodhouse Lane
Quarry Lane
Station Close
"""


listNames = names.splitlines()
listAddresses = stringAddresses.splitlines()

from random import choices, randint
numberRecords = 20 # some input
chosenNames = choices(listNames, k=numberRecords)

# now we need to choose some addresses for the names
chosenAdresses = choices(listAddresses, k=numberRecords)

# now we need to put some numbers on the addresses to make them seem real
# and a new list to go with the numbers
numberedAdresses = []
for i in chosenAdresses:
    i += f' {randint(2,9000)}'
    numberedAdresses.append(i)
# print(numberedAdresses)

# now we needed to combine them
table = []
tmpList = []
for i in chosenNames:
    tmpList.append(i)
    tmpList.append(numberedAdresses[chosenNames.index(i)])
    table.append(tmpList)
    tmpList = []

# print(table)

# now we need a semi realistic phone number for each 
# to do this we'll assume the phone number is of the form: xxx-xxx-xxxx
# so we can just generate 3 numbers in two ranges 100-999 and 1000-9999
for i in table:
    num1 = randint(100, 999)
    num2 = randint(100, 999)
    num3 = randint(1000, 9999)
    phoneNumberTmp = f'{num1}{num2}{num3}'
    i.append(phoneNumberTmp)

for i in table:
    print(i)